title: SuitUp PHP Framework
description: Legendary web applications \n (productivity and quickly apps starts here)
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
